version: 2
jobs:
  build:
    docker:
        - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
        - checkout
        - run:
            name: create-dependency-cache-manifest
            command: cat package.json packages/*/package.json > dependency.manifest
        - restore_cache:
            key: dependency-cache-{{ checksum "dependency.manifest" }}
        - run:
            name: install-dependencies-if-necessary
            command: |
              if [ ! -d "node_modules" ]; then
                npm install
                npm run bootstrap
              fi
        - save_cache:
            key: dependency-cache-{{ checksum "dependency.manifest" }}
            paths:
                - ./node_modules
                - ./packages/*/node_modules
        - run:
            name: lint
            command: npm lint
        - run:
            name: test
            command: npm test
