version: 2
jobs:
  build:
    docker:
        - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
        - checkout
        - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'
        - restore_dependency_cache:
            key: dependency-cache-{{ checksum "package.json" }}
        - run:
            name: npm-install
            command: npm install
        - save_dependency_cache:
            key: dependency-cache-{{ checksum "package.json" }}
            paths:
                - ./packages/**/node_modules
        - restore_bootstrap_cache:
            key: bootstrap-cache-{{ checksum "packages/**/package.json" }}
        - run:
            name: npm-install
            command: npm install
        - save_bootstrap_cache:
            key: bootstrap-cache-{{ checksum "packages/**/package.json" }}
            paths:
                - ./packages/**/node_modules
        - run:
            name: test
            command: npm test
