version: 2
jobs:
  build:
    docker:
        - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
        - checkout
        - run:
            name: install-apps
            working_directory: /
            command: |
                apt-get -y -qq update
                apt install python-pip python-dev
                pip install awscli
        - run:
            name: install-dependencies
            command: npm install
        - run:
            name: lint
            command: npm run lint
        - run:
            name: test
            command: npm run test
        - run:
            name: deploy
            command: npm run deploy
