version: 2
jobs:
  build:
    docker:
        - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
        - checkout
        - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'
        - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}
        - run:
            name: npm-install
            command: npm install
        - save_cache:
            key: dependency-cache-{{ checksum "package.json" }}
            paths:
                - ./packages/*/node_modules
        - run:
            name: create-bootstrap-cache-manifest
            command: cat packages/**/package.json > bootstrap.json
        - restore_cache:
            key: bootstrap-cache-{{ checksum "bootstrap.json" }}
        - run:
            name: lerna-bootstrap
            command: npm run bootstrap
        - save_cache:
            key: bootstrap-cache-{{ checksum "bootstrap.json" }}
            paths:
                - ./packages/*/node_modules
        - run:
            name: test
            command: npm test
