version: 2
jobs:
  build:
    docker:
        - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
        - checkout
        - run:
            name: npm-install
            command: npm install
        - run:
            name: lerna-bootstrap
            command: npm run bootstrap
        - run:
            name: test
            command: npm test
